### ISSUE TITLE
lag/slow

### ISSUE THREAD

**Issue by dragonhacker22** [AzizKpln/Whistleye_Project#1]
Hello
The site is very good but the background take a lot of vram and cpu usage and I'm using raspberry pi 3 so it's not that powerful specs because of this it's lagging, so I wish if can add a mod or a button that disable the back ground or make terminal edition just like Moriarty-Project.
Thanks

**Comment by AzizKpln** [comment]
yes i can add a background changer button.

**Comment by dragonhacker22** [comment]
ok, thank you😊

**Comment by AzizKpln** [comment]
im working on it right now. But i need to make extra changes in codes so, update may take a few days. But i'll let u know when it's done.

**Comment by AzizKpln** [comment]
okay it's updated. You can use the website without background or, you can change the background image randomly.

**Comment by dragonhacker22** [comment]
It's a lot better right now
But when I Disable or change the background the site disable it in one page only and when go to another page it enable it again or back to the original background
So can you make the button disable all in the all site instead of one page ?
and thanks for your efforts 😊

**Comment by AzizKpln** [comment]
i dont have time for that but i updated moriarty to v2.5 recently
https://github.com/AzizKpln/Moriarty-Project
